//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFStatistics3
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCustomer
    {
        public TblCustomer()
        {
            this.TblOrder = new HashSet<TblOrder>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerCountry { get; set; }
    
        public virtual ICollection<TblOrder> TblOrder { get; set; }
    }
}
